version: '3.8'

services:
  # db for every scrape target
  autotrader-db:
    image: postgres:15.1
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: ${AUTOTRADER_POSTGRES_PASSWORD}
      POSTGRES_USER: ${AUTOTRADER_POSTGRES_USER}
    networks:
      - private

networks:
  private:
