version: '3.8'

services:
  autotrader-db:
    image: postgres:15.1
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: ${AUTOTRADER_POSTGRES_PASSWORD}
      POSTGRES_USER: ${AUTOTRADER_POSTGRES_USER}
    networks:
      - private
    volumes:
      - autotrader-db-vol:/var/lib/postgresql/data

  carmax-db:
    image: postgres:15.1
    ports:
      - 25432:5432
    environment:
      POSTGRES_PASSWORD: ${CARMAX_POSTGRES_PASSWORD}
      POSTGRES_USER: ${CARMAX_POSTGRES_USER}
    networks:
      - private
    volumes:
      - carmax-db-vol:/var/lib/postgresql/data

  carvana-db:
    image: postgres:15.1
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: ${CARVANA_POSTGRES_PASSWORD}
      POSTGRES_USER: ${CARVANA_POSTGRES_USER}
    networks:
      - private
    volumes:
      - carvana-db-vol:/var/lib/postgresql/data

networks:
  private:

volumes:
  autotrader-db-vol:
  carmax-db-vol:
  carvana-db-vol: