version: '3.8'

services:
  db:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - private


networks:
  private:
